# Generated by Django 4.0.5 on 2022-06-09 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nota_fiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeProd', models.CharField(max_length=100)),
                ('quantidade', models.CharField(max_length=6)),
                ('email', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=13)),
                ('CNPJ', models.CharField(max_length=100)),
            ],
        ),
    ]
